Require gio-unix-2.0 instead of gio-2.0
This fixes the following on NixOS:

AppInfos.hpp:13:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
   13 | #include <gio/gdesktopappinfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

The reason here is the same as https://gitlab.xfce.org/xfce/xfce4-session/-/merge_requests/51.
It looks only gio/gdesktopappinfo.h is used here.